export const SET_FILTER = 'SET_FILTER';

// categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

// recipes
export const DISPLAY_RECIPE = 'DISPLAY_RECIPE';
export const GET_RECIPE_SUCCESS = 'GET_RECIPE_SUCCESS';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';