export const SET_FILTER = 'SET_FILTER';

// categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

// recipes
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const TOGGLE_RECIPE_FINISH = 'TOGGLE_RECIPE_FINISH';
export const TOGGLE_RECIPE_INGREDIENT = 'TOGGLE_RECIPE_INGREDIENT';
export const TOGGLE_RECIPE_METHOD = 'TOGGLE_RECIPE_METHOD';
